### ISSUE TITLE
Crash when using JEI

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [zerofall/EZStorage2#6]
I shift clicked a recipe for ender io into the crafting monitor from EZ2, game froze and crashed, cant tell if this is an issue with EZ or JEI, but Jei works with anything else. here is the log that makes me think its you, 
forge:2000
minecraft:1.10
Ez2: 2.0.2

java.lang.NoClassDefFoundError: mezz/jei/gui/ingredients/IGuiIngredient
	at com.zerofall.ezstorage.jei.RecipeTransferHandler.transferRecipe(RecipeTransferHandler.java:43)
	at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:35)
	at mezz.jei.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:21)
	at mezz.jei.gui.RecipesGui.func_146284_a(RecipesGui.java:429)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:458)
	at mezz.jei.gui.RecipesGui.func_73864_a(RecipesGui.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:546)
	at mezz.jei.gui.RecipesGui.func_146274_d(RecipesGui.java:275)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:515)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mezz.jei.gui.ingredients.IGuiIngredient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by sblectric** [comment]
This is related to JEI internals changing in 1.10 and up. Will be fixed in the next release.

**Comment by sblectric** [comment]
Fixed in 2.0.3.

**Comment by EPIICTHUNDERCAT** [comment]
Cool, thanks and very fast. good job

**Comment by sblectric** [comment]
Sure, I try!
